branches:
    - master

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 🚀 Features
    label: feature
  - title: 🐛 Bug Fixes
    label: fix
  - title: 🧰 Maintenance
    label: chore
include-labels:
  - 'feature'
  - 'fix'
  - 'chore'
no-changes-template: '* No changes'
template: |
  ## What’s Changed

  $CHANGES